# import = ["~/.config/alacritty/base16_default_dark.toml"]
# import = ["~/.config/alacritty/citylights.toml"] 

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
style = "SemiBold"

[font.normal]
family = "Droid Sans Mono"
style = "Regular"


[window]
opacity = 0.9

[window.padding]
x = 8
y = 8

[terminal]
